# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea9e92ca235d2b0604db71cc83ce5e102b4214efe802c1ee2bcc483617814a420ee9c25ea2602d2a0ef06eabc4472bf43aaa86518776cac7077c3585d8325585

test:
  secret_key_base: 4c19e7f8bd453ed989fc5ba0cade02e1bedd65d4d1e57b934c52ce05e31fc047771efe50b85402228b3cc76e92fe2faada49978d55f2a237eab2eb3dc6277729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
